import React, { useContext, useEffect } from 'react';
import { Button } from './ui/Button';
import { Card } from './ui/Card';
import { PracticeSetupModal } from './PracticeSetupModal';
import { AppContext } from '../context/AppContext';
import { Language, SnippetLength, SnippetLevel } from '../types';

interface HomePageProps {
  onStartPractice: () => void;
}

const FeatureCard: React.FC<{title: string; description: string; icon: string}> = ({ title, description, icon }) => (
    <Card className="p-6 text-center">
        <div className="text-4xl mb-4 text-primary-500">{icon}</div>
        <h3 className="text-xl font-semibold mb-2">{title}</h3>
        <p className="text-gray-600 dark:text-gray-400">{description}</p>
    </Card>
);

const HomePage: React.FC<HomePageProps> = ({ onStartPractice }) => {
  const context = useContext(AppContext);
  if (!context) throw new Error("AppContext not found");
  
  const { 
    startCustomSession,
    fetchNewSnippet,
    isSetupModalOpen,
    openSetupModal,
    closeSetupModal,
  } = context;

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (isSetupModalOpen || (e.target as HTMLElement).closest('input, textarea, select, button')) return;

      if (
        e.key === 'Enter' ||
        e.key === ' ' ||
        (e.key === 'Enter' && e.ctrlKey)
      ) {
        e.preventDefault();
        openSetupModal();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [isSetupModalOpen, openSetupModal]);

  const handleStartSetup = (length: SnippetLength | null, level: SnippetLevel | null, customCode: string | null) => {
    closeSetupModal();
    if (customCode) {
      startCustomSession(customCode);
    } else if (length && level) {
      // Pass length and level directly to prevent race condition.
      fetchNewSnippet({ length, level });
    }
    onStartPractice();
  };

  return (
    <>
      <div className="h-full overflow-y-auto custom-scrollbar">
        <div className="text-center py-12">
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold tracking-tight mb-4">
            Sharpen Your{' '}
            <span className="text-primary-600 dark:text-primary-400">Coding Speed</span>
          </h1>
          <p className="max-w-2xl mx-auto text-lg text-gray-600 dark:text-gray-300 mb-8">
            Practice typing real code snippets generated by AI. Boost your accuracy, increase your WPM, and master your favorite programming language's syntax.
          </p>
          <Button size="lg" onClick={openSetupModal}>
            Start Practicing Now
          </Button>

          <div className="mt-20 grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            <FeatureCard 
                title="AI-Powered Snippets"
                description="Endless, unique practice sessions with code generated by Google's Gemini."
                icon="🧠"
            />
            <FeatureCard 
                title="Real-time Feedback"
                description="Instantly track your Words Per Minute (WPM) and typing accuracy as you go."
                icon="📊"
            />
            <FeatureCard 
                title="Syntax Focused"
                description="Get comfortable with language-specific syntax, not just random words."
                icon="💻"
            />
          </div>
        </div>
      </div>

      <PracticeSetupModal 
        isOpen={isSetupModalOpen}
        onClose={closeSetupModal}
        onStart={handleStartSetup}
        variant="default"
      />
    </>
  );
};

export default HomePage;