import React, { useContext, useEffect } from 'react';
import { Button } from './ui/Button';
import { Card } from './ui/Card';
import { AppContext } from '../context/AppContext';
import { Language, SnippetLength, SnippetLevel, PracticeMode } from '../types';

interface HomePageProps {
  onStartPractice: () => void;
}

const FeatureCard: React.FC<{ title: string; description: string; icon: string }> = ({ title, description, icon }) => (
  <Card className="p-6 text-center hover:scale-105 transition-transform duration-300">
    <div className="text-5xl mb-4">{icon}</div>
    <h3 className="text-xl font-semibold mb-2 bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 dark:from-indigo-400 dark:via-purple-400 dark:to-pink-400 bg-clip-text text-transparent">{title}</h3>
    <p className="text-slate-600 dark:text-slate-400">{description}</p>
  </Card>
);

const HomePage: React.FC<HomePageProps> = ({ onStartPractice }) => {
  const context = useContext(AppContext);
  if (!context) throw new Error("AppContext not found");

  const {
    startCustomSession,
    fetchNewSnippet,
    isSetupModalOpen,
    openSetupModal,
    closeSetupModal,
  } = context;

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (isSetupModalOpen || (e.target as HTMLElement).closest('input, textarea, select, button')) return;

      if (
        e.key === 'Enter' ||
        e.key === ' ' ||
        (e.key === 'Enter' && e.ctrlKey)
      ) {
        e.preventDefault();
        openSetupModal();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [isSetupModalOpen, openSetupModal]);

  const handleStartSetup = (length: SnippetLength | null, level: SnippetLevel | null, customCode: string | null, mode?: PracticeMode) => {
    closeSetupModal();
    if (customCode) {
      startCustomSession(customCode, mode);
    } else if (length && level) {
      fetchNewSnippet({ length, level, mode });
    }
    onStartPractice();
  };

  return (
    <>
      <div className="h-full overflow-y-auto custom-scrollbar">
        {/* Hero Section */}
        <div className="relative min-h-[70vh] flex items-center justify-center px-4 py-12">
          {/* Decorative gradient orbs */}
          <div className="absolute top-20 left-10 w-72 h-72 bg-gradient-to-r from-indigo-400 to-purple-400 rounded-full blur-3xl opacity-20 animate-pulse" />
          <div className="absolute bottom-20 right-10 w-96 h-96 bg-gradient-to-r from-purple-400 to-pink-400 rounded-full blur-3xl opacity-20 animate-pulse" style={{ animationDelay: '1s' }} />

          <div className="relative z-10 text-center max-w-5xl mx-auto">
            {/* Badge */}
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass mb-8 animate-fade-in-up">
              <span className="text-2xl">✨</span>
              <span className="text-sm font-medium bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 dark:from-indigo-400 dark:via-purple-400 dark:to-pink-400 bg-clip-text text-transparent">
                AI-Powered Typing Practice
              </span>
            </div>

            {/* Main Heading */}
            <h1 className="text-5xl sm:text-6xl md:text-7xl lg:text-8xl font-extrabold tracking-tight mb-6 leading-tight">
              <span className="text-slate-900 dark:text-white">
                Sharpen Your
              </span>
              <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 animate-fade-in-up">
                Coding Speed
              </span>
            </h1>

            {/* Subtitle */}
            <p className="max-w-2xl mx-auto text-lg md:text-xl text-slate-600 dark:text-slate-300 mb-10 animate-fade-in-up" style={{ animationDelay: '0.2s' }}>
              Practice typing real code snippets generated by AI. Boost your accuracy, increase your WPM, and master your favorite programming language's syntax.
            </p>

            {/* CTA Button */}
            <div className="animate-fade-in-up" style={{ animationDelay: '0.3s' }}>
              <Button
                size="lg"
                onClick={openSetupModal}
                className="text-lg px-8 py-4 group"
              >
                Start Practicing Now
                <svg className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                </svg>
              </Button>
            </div>

            {/* Stats */}
            <div className="mt-16 flex items-center justify-center gap-8 md:gap-16 animate-fade-in" style={{ animationDelay: '0.5s' }}>
              {[
                { value: '10+', label: 'Languages' },
                { value: 'AI', label: 'Generated' },
                { value: '∞', label: 'Practice' },
              ].map((stat, i) => (
                <div key={i} className="text-center">
                  <div className="text-2xl md:text-3xl font-bold bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 dark:from-indigo-400 dark:via-purple-400 dark:to-pink-400 bg-clip-text text-transparent">
                    {stat.value}
                  </div>
                  <div className="text-sm text-slate-500 dark:text-slate-400">
                    {stat.label}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Features Section */}
        <div className="max-w-6xl mx-auto px-4 py-20">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <FeatureCard
              title="AI-Powered Snippets"
              description="Endless, unique practice sessions with code generated by Google's Gemini."
              icon="🧠"
            />
            <FeatureCard
              title="Real-time Feedback"
              description="Instantly track your Words Per Minute (WPM) and typing accuracy as you go."
              icon="📊"
            />
            <FeatureCard
              title="Syntax Focused"
              description="Get comfortable with language-specific syntax, not just random words."
              icon="💻"
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default HomePage;